// <auto-generated />
using System;
using Konyvtar.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Konyvtar.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20250930205126_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Konyvtar.Model.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.Property<bool>("InStock")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PublishedYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ISBN")
                        .IsUnique();

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Gárdonyi Géza",
                            CreatedAt = new DateTime(2025, 9, 30, 20, 51, 26, 88, DateTimeKind.Utc).AddTicks(2347),
                            ISBN = "1234567890123",
                            InStock = true,
                            Price = 3500.00m,
                            PublishedYear = 1901,
                            Title = "Egri csillagok"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Molnár Ferenc",
                            CreatedAt = new DateTime(2025, 9, 30, 20, 51, 26, 88, DateTimeKind.Utc).AddTicks(2350),
                            ISBN = "9876543210987",
                            InStock = true,
                            Price = 2800.50m,
                            PublishedYear = 1907,
                            Title = "A Pál utcai fiúk"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Madách Imre",
                            CreatedAt = new DateTime(2025, 9, 30, 20, 51, 26, 88, DateTimeKind.Utc).AddTicks(2351),
                            ISBN = "4567891234567",
                            InStock = false,
                            Price = 4200.75m,
                            PublishedYear = 1861,
                            Title = "Az ember tragédiája"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Fekete István",
                            CreatedAt = new DateTime(2025, 9, 30, 20, 51, 26, 88, DateTimeKind.Utc).AddTicks(2353),
                            ISBN = "3216549870123",
                            InStock = true,
                            Price = 3100.00m,
                            PublishedYear = 1957,
                            Title = "Tüskevár"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
